import { MonthlyData, User } from '@/types/carbon';

export interface Panchayat {
  id: string;
  name: string;
  district: string;
  state: string;
  totalPopulation: number;
}

export const mockPanchayats: Panchayat[] = [
  { id: 'p1', name: 'Gram Panchayat Chandpur', district: 'Varanasi', state: 'Uttar Pradesh', totalPopulation: 4500 },
  { id: 'p2', name: 'Gram Panchayat Ramgarh', district: 'Lucknow', state: 'Uttar Pradesh', totalPopulation: 3200 },
  { id: 'p3', name: 'Gram Panchayat Sundarpur', district: 'Patna', state: 'Bihar', totalPopulation: 5100 },
  { id: 'p4', name: 'Gram Panchayat Greenville', district: 'Jaipur', state: 'Rajasthan', totalPopulation: 2800 },
  { id: 'p5', name: 'Gram Panchayat Lakeview', district: 'Bhopal', state: 'Madhya Pradesh', totalPopulation: 3900 },
];

export const mockUsers: User[] = [
  { id: '1', username: 'admin', role: 'admin', panchayatId: undefined },
  { id: '2', username: 'chandpur_user', role: 'user', panchayatId: 'p1' },
  { id: '3', username: 'ramgarh_user', role: 'user', panchayatId: 'p2' },
  { id: '4', username: 'sundarpur_user', role: 'user', panchayatId: 'p3' },
  { id: '5', username: 'greenville_user', role: 'user', panchayatId: 'p4' },
  { id: '6', username: 'lakeview_user', role: 'user', panchayatId: 'p5' },
];

export const mockMonthlyData: MonthlyData[] = [
  // Chandpur data
  {
    id: '1',
    userId: '2',
    panchayatId: 'p1',
    month: 'Jan',
    year: 2024,
    electricityKwh: 450,
    dieselLiters: 120,
    petrolLiters: 80,
    wasteKg: 200,
    waterLiters: 15000,
    solarUnits: 100,
    treesPlanted: 15,
    createdAt: new Date('2024-01-31'),
  },
  {
    id: '2',
    userId: '2',
    panchayatId: 'p1',
    month: 'Feb',
    year: 2024,
    electricityKwh: 420,
    dieselLiters: 100,
    petrolLiters: 75,
    wasteKg: 180,
    waterLiters: 14000,
    solarUnits: 120,
    treesPlanted: 20,
    createdAt: new Date('2024-02-28'),
  },
  {
    id: '3',
    userId: '2',
    panchayatId: 'p1',
    month: 'Mar',
    year: 2024,
    electricityKwh: 480,
    dieselLiters: 130,
    petrolLiters: 90,
    wasteKg: 220,
    waterLiters: 16000,
    solarUnits: 140,
    treesPlanted: 25,
    createdAt: new Date('2024-03-31'),
  },
  // Ramgarh data
  {
    id: '4',
    userId: '3',
    panchayatId: 'p2',
    month: 'Jan',
    year: 2024,
    electricityKwh: 380,
    dieselLiters: 90,
    petrolLiters: 60,
    wasteKg: 150,
    waterLiters: 12000,
    solarUnits: 80,
    treesPlanted: 10,
    createdAt: new Date('2024-01-31'),
  },
  {
    id: '5',
    userId: '3',
    panchayatId: 'p2',
    month: 'Feb',
    year: 2024,
    electricityKwh: 360,
    dieselLiters: 85,
    petrolLiters: 55,
    wasteKg: 140,
    waterLiters: 11000,
    solarUnits: 90,
    treesPlanted: 12,
    createdAt: new Date('2024-02-28'),
  },
  // Sundarpur data
  {
    id: '6',
    userId: '4',
    panchayatId: 'p3',
    month: 'Jan',
    year: 2024,
    electricityKwh: 520,
    dieselLiters: 150,
    petrolLiters: 100,
    wasteKg: 250,
    waterLiters: 18000,
    solarUnits: 60,
    treesPlanted: 8,
    createdAt: new Date('2024-01-31'),
  },
  {
    id: '7',
    userId: '4',
    panchayatId: 'p3',
    month: 'Feb',
    year: 2024,
    electricityKwh: 500,
    dieselLiters: 140,
    petrolLiters: 95,
    wasteKg: 230,
    waterLiters: 17000,
    solarUnits: 70,
    treesPlanted: 10,
    createdAt: new Date('2024-02-28'),
  },
  // Greenville data
  {
    id: '8',
    userId: '5',
    panchayatId: 'p4',
    month: 'Jan',
    year: 2024,
    electricityKwh: 300,
    dieselLiters: 70,
    petrolLiters: 50,
    wasteKg: 120,
    waterLiters: 10000,
    solarUnits: 150,
    treesPlanted: 25,
    createdAt: new Date('2024-01-31'),
  },
  {
    id: '9',
    userId: '5',
    panchayatId: 'p4',
    month: 'Feb',
    year: 2024,
    electricityKwh: 280,
    dieselLiters: 65,
    petrolLiters: 45,
    wasteKg: 110,
    waterLiters: 9500,
    solarUnits: 160,
    treesPlanted: 30,
    createdAt: new Date('2024-02-28'),
  },
  // Lakeview data
  {
    id: '10',
    userId: '6',
    panchayatId: 'p5',
    month: 'Jan',
    year: 2024,
    electricityKwh: 400,
    dieselLiters: 95,
    petrolLiters: 70,
    wasteKg: 160,
    waterLiters: 13000,
    solarUnits: 110,
    treesPlanted: 18,
    createdAt: new Date('2024-01-31'),
  },
  {
    id: '11',
    userId: '6',
    panchayatId: 'p5',
    month: 'Feb',
    year: 2024,
    electricityKwh: 380,
    dieselLiters: 90,
    petrolLiters: 65,
    wasteKg: 150,
    waterLiters: 12500,
    solarUnits: 120,
    treesPlanted: 20,
    createdAt: new Date('2024-02-28'),
  },
  {
    id: '12',
    userId: '2',
    panchayatId: 'p1',
    month: 'Apr',
    year: 2024,
    electricityKwh: 400,
    dieselLiters: 95,
    petrolLiters: 70,
    wasteKg: 160,
    waterLiters: 13000,
    solarUnits: 160,
    treesPlanted: 30,
    createdAt: new Date('2024-04-30'),
  },
  {
    id: '13',
    userId: '2',
    panchayatId: 'p1',
    month: 'May',
    year: 2024,
    electricityKwh: 380,
    dieselLiters: 85,
    petrolLiters: 65,
    wasteKg: 150,
    waterLiters: 12000,
    solarUnits: 180,
    treesPlanted: 35,
    createdAt: new Date('2024-05-31'),
  },
  {
    id: '14',
    userId: '2',
    panchayatId: 'p1',
    month: 'Jun',
    year: 2024,
    electricityKwh: 350,
    dieselLiters: 75,
    petrolLiters: 60,
    wasteKg: 140,
    waterLiters: 11000,
    solarUnits: 200,
    treesPlanted: 40,
    createdAt: new Date('2024-06-30'),
  },
];
